# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
